import type { PatternKey } from './demoPatternTypes'

interface ApgExampleCoverage {
  readonly apgPattern: string
  readonly example: string
  readonly demoPattern: PatternKey
  readonly variant?: string
}

export const officialApgExamples = {
  accordion: ['accordion'],
  alert: ['alert'],
  alertdialog: ['alertdialog'],
  breadcrumb: ['breadcrumb'],
  button: ['button', 'button_idl'],
  carousel: ['carousel-1-prev-next', 'carousel-2-tablist'],
  checkbox: ['checkbox', 'checkbox-mixed'],
  combobox: [
    'combobox-autocomplete-both',
    'combobox-autocomplete-list',
    'combobox-autocomplete-none',
    'combobox-datepicker',
    'combobox-select-only',
    'grid-combo',
  ],
  'dialog-modal': ['datepicker-dialog', 'dialog'],
  disclosure: [
    'disclosure-card',
    'disclosure-faq',
    'disclosure-image-description',
    'disclosure-navigation',
    'disclosure-navigation-hybrid',
  ],
  feed: ['feed', 'feed-display'],
  grid: ['advanced-data-grid', 'data-grids', 'layout-grids'],
  landmarks: [
    'HTML5',
    'at',
    'banner',
    'complementary',
    'contentinfo',
    'form',
    'general-principles',
    'main',
    'navigation',
    'region',
    'resources',
    'search',
  ],
  link: ['link'],
  listbox: ['listbox-collapsible', 'listbox-grouped', 'listbox-rearrangeable', 'listbox-scrollable'],
  'menu-button': ['menu-button-actions', 'menu-button-actions-active-descendant', 'menu-button-links'],
  menubar: ['menubar-editor', 'menubar-navigation'],
  meter: ['meter'],
  radio: ['radio', 'radio-activedescendant', 'radio-rating'],
  'slider-multithumb': ['slider-multithumb'],
  slider: ['slider-color-viewer', 'slider-rating', 'slider-seek', 'slider-temperature'],
  spinbutton: ['datepicker-spinbuttons', 'quantity-spinbutton'],
  switch: ['switch', 'switch-button', 'switch-checkbox'],
  table: ['sortable-table', 'table'],
  tabs: ['tabs-actions', 'tabs-automatic', 'tabs-manual'],
  toolbar: ['help', 'toolbar'],
  treegrid: ['treegrid-1'],
  treeview: ['treeview-1a', 'treeview-1b', 'treeview-navigation'],
} as const satisfies Record<string, readonly string[]>

export const apgExampleCoverage: readonly ApgExampleCoverage[] = [
  { apgPattern: 'accordion', example: 'accordion', demoPattern: 'accordion' },
  { apgPattern: 'alert', example: 'alert', demoPattern: 'alert' },
  { apgPattern: 'alertdialog', example: 'alertdialog', demoPattern: 'alertdialog' },
  { apgPattern: 'breadcrumb', example: 'breadcrumb', demoPattern: 'breadcrumb' },
  { apgPattern: 'button', example: 'button', demoPattern: 'button', variant: 'action' },
  { apgPattern: 'button', example: 'button_idl', demoPattern: 'button', variant: 'action' },
  { apgPattern: 'carousel', example: 'carousel-1-prev-next', demoPattern: 'carousel', variant: 'previousNext' },
  { apgPattern: 'carousel', example: 'carousel-2-tablist', demoPattern: 'carousel', variant: 'tablist' },
  { apgPattern: 'checkbox', example: 'checkbox', demoPattern: 'checkbox', variant: 'twoState' },
  { apgPattern: 'checkbox', example: 'checkbox-mixed', demoPattern: 'checkbox', variant: 'triState' },
  { apgPattern: 'combobox', example: 'combobox-autocomplete-both', demoPattern: 'combobox', variant: 'listWithInlineAutocomplete' },
  { apgPattern: 'combobox', example: 'combobox-autocomplete-list', demoPattern: 'combobox', variant: 'listAutocomplete' },
  { apgPattern: 'combobox', example: 'combobox-autocomplete-none', demoPattern: 'combobox', variant: 'listNoAutocomplete' },
  { apgPattern: 'combobox', example: 'combobox-datepicker', demoPattern: 'combobox', variant: 'datepicker' },
  { apgPattern: 'combobox', example: 'combobox-select-only', demoPattern: 'combobox', variant: 'selectOnly' },
  { apgPattern: 'combobox', example: 'grid-combo', demoPattern: 'combobox', variant: 'gridPopup' },
  { apgPattern: 'dialog-modal', example: 'datepicker-dialog', demoPattern: 'dialog', variant: 'datepicker' },
  { apgPattern: 'dialog-modal', example: 'dialog', demoPattern: 'dialog' },
  { apgPattern: 'disclosure', example: 'disclosure-card', demoPattern: 'disclosure', variant: 'simple' },
  { apgPattern: 'disclosure', example: 'disclosure-faq', demoPattern: 'disclosure', variant: 'faq' },
  { apgPattern: 'disclosure', example: 'disclosure-image-description', demoPattern: 'disclosure', variant: 'image' },
  { apgPattern: 'disclosure', example: 'disclosure-navigation', demoPattern: 'disclosure', variant: 'navMenu' },
  { apgPattern: 'disclosure', example: 'disclosure-navigation-hybrid', demoPattern: 'disclosure', variant: 'navMenuTopLinks' },
  { apgPattern: 'feed', example: 'feed', demoPattern: 'feed' },
  { apgPattern: 'feed', example: 'feed-display', demoPattern: 'feed' },
  { apgPattern: 'grid', example: 'advanced-data-grid', demoPattern: 'grid', variant: 'dataAdvanced' },
  { apgPattern: 'grid', example: 'data-grids', demoPattern: 'grid', variant: 'dataTransactions' },
  { apgPattern: 'grid', example: 'layout-grids', demoPattern: 'grid', variant: 'layoutLinks' },
  { apgPattern: 'landmarks', example: 'HTML5', demoPattern: 'landmarks', variant: 'html5' },
  { apgPattern: 'landmarks', example: 'at', demoPattern: 'landmarks', variant: 'all' },
  { apgPattern: 'landmarks', example: 'banner', demoPattern: 'landmarks', variant: 'banner' },
  { apgPattern: 'landmarks', example: 'complementary', demoPattern: 'landmarks', variant: 'complementary' },
  { apgPattern: 'landmarks', example: 'contentinfo', demoPattern: 'landmarks', variant: 'contentinfo' },
  { apgPattern: 'landmarks', example: 'form', demoPattern: 'landmarks', variant: 'form' },
  { apgPattern: 'landmarks', example: 'general-principles', demoPattern: 'landmarks', variant: 'general' },
  { apgPattern: 'landmarks', example: 'main', demoPattern: 'landmarks', variant: 'main' },
  { apgPattern: 'landmarks', example: 'navigation', demoPattern: 'landmarks', variant: 'navigation' },
  { apgPattern: 'landmarks', example: 'region', demoPattern: 'landmarks', variant: 'region' },
  { apgPattern: 'landmarks', example: 'resources', demoPattern: 'landmarks', variant: 'resources' },
  { apgPattern: 'landmarks', example: 'search', demoPattern: 'landmarks', variant: 'search' },
  { apgPattern: 'link', example: 'link', demoPattern: 'link', variant: 'anchor' },
  { apgPattern: 'listbox', example: 'listbox-collapsible', demoPattern: 'listbox', variant: 'collapsible' },
  { apgPattern: 'listbox', example: 'listbox-grouped', demoPattern: 'listbox', variant: 'grouped' },
  { apgPattern: 'listbox', example: 'listbox-rearrangeable', demoPattern: 'listbox', variant: 'rearrangeable' },
  { apgPattern: 'listbox', example: 'listbox-scrollable', demoPattern: 'listbox', variant: 'scrollable' },
  { apgPattern: 'menu-button', example: 'menu-button-actions', demoPattern: 'menu', variant: 'actionMenuButton' },
  { apgPattern: 'menu-button', example: 'menu-button-actions-active-descendant', demoPattern: 'menu', variant: 'actionMenuButtonActiveDescendant' },
  { apgPattern: 'menu-button', example: 'menu-button-links', demoPattern: 'menu', variant: 'linkMenuButton' },
  { apgPattern: 'menubar', example: 'menubar-editor', demoPattern: 'menu', variant: 'editorMenubar' },
  { apgPattern: 'menubar', example: 'menubar-navigation', demoPattern: 'menu', variant: 'navMenubar' },
  { apgPattern: 'meter', example: 'meter', demoPattern: 'meter' },
  { apgPattern: 'radio', example: 'radio', demoPattern: 'radio', variant: 'rovingTabindex' },
  { apgPattern: 'radio', example: 'radio-activedescendant', demoPattern: 'radio', variant: 'ariaActiveDescendant' },
  { apgPattern: 'radio', example: 'radio-rating', demoPattern: 'radio', variant: 'rating' },
  { apgPattern: 'slider-multithumb', example: 'slider-multithumb', demoPattern: 'slider', variant: 'range' },
  { apgPattern: 'slider', example: 'slider-color-viewer', demoPattern: 'slider', variant: 'color' },
  { apgPattern: 'slider', example: 'slider-rating', demoPattern: 'slider', variant: 'rating' },
  { apgPattern: 'slider', example: 'slider-seek', demoPattern: 'slider', variant: 'seek' },
  { apgPattern: 'slider', example: 'slider-temperature', demoPattern: 'slider', variant: 'temperature' },
  { apgPattern: 'spinbutton', example: 'datepicker-spinbuttons', demoPattern: 'spinbutton', variant: 'time' },
  { apgPattern: 'spinbutton', example: 'quantity-spinbutton', demoPattern: 'spinbutton', variant: 'numeric' },
  { apgPattern: 'switch', example: 'switch', demoPattern: 'switch', variant: 'switch' },
  { apgPattern: 'switch', example: 'switch-button', demoPattern: 'switch', variant: 'button' },
  { apgPattern: 'switch', example: 'switch-checkbox', demoPattern: 'switch', variant: 'checkbox' },
  { apgPattern: 'table', example: 'sortable-table', demoPattern: 'table', variant: 'sortable' },
  { apgPattern: 'table', example: 'table', demoPattern: 'table', variant: 'basic' },
  { apgPattern: 'tabs', example: 'tabs-actions', demoPattern: 'tabs', variant: 'closeable' },
  { apgPattern: 'tabs', example: 'tabs-automatic', demoPattern: 'tabs', variant: 'automatic' },
  { apgPattern: 'tabs', example: 'tabs-manual', demoPattern: 'tabs', variant: 'manual' },
  { apgPattern: 'toolbar', example: 'help', demoPattern: 'toolbar', variant: 'help' },
  { apgPattern: 'toolbar', example: 'toolbar', demoPattern: 'toolbar' },
  { apgPattern: 'treegrid', example: 'treegrid-1', demoPattern: 'treegrid' },
  { apgPattern: 'treeview', example: 'treeview-1a', demoPattern: 'treeview', variant: 'fileDirectoryComputed' },
  { apgPattern: 'treeview', example: 'treeview-1b', demoPattern: 'treeview', variant: 'fileDirectoryDeclared' },
  { apgPattern: 'treeview', example: 'treeview-navigation', demoPattern: 'treeview', variant: 'navigation' },
] as const

export function exampleId(apgPattern: string, example: string) {
  return `${apgPattern}/${example}`
}
