export const ds = {
  focusRing: 'outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 data-[focus-visible]:outline data-[focus-visible]:outline-2 data-[focus-visible]:outline-offset-2 data-[focus-visible]:outline-zinc-400 dark:focus-visible:outline-zinc-500 dark:data-[focus-visible]:outline-zinc-500',
  focusRingInset: 'outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-zinc-400 data-[focus-visible]:outline data-[focus-visible]:outline-2 data-[focus-visible]:outline-offset-[-2px] data-[focus-visible]:outline-zinc-400 dark:focus-visible:outline-zinc-500 dark:data-[focus-visible]:outline-zinc-500',
  panel: 'min-h-0 rounded-xl bg-white/92 p-3 shadow-[0_16px_48px_rgba(24,24,27,0.07)] backdrop-blur dark:bg-zinc-950/90 dark:shadow-[0_18px_54px_rgba(0,0,0,0.34)]',
  field: 'h-8 w-full rounded-lg bg-zinc-100/75 px-2.5 text-sm shadow-inner shadow-zinc-200/40 outline-none transition focus:bg-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 dark:bg-white/[0.06] dark:shadow-black/20 dark:focus:bg-white/[0.08] dark:focus-visible:outline-zinc-500',
  codeBlock: 'max-h-[44dvh] min-h-0 overflow-auto rounded-xl bg-zinc-950 p-4 pr-12 font-mono text-[11px] leading-5 text-zinc-200 shadow-inner shadow-black/30 lg:h-full lg:max-h-none',
  dataBlock: 'max-h-[44dvh] min-h-0 overflow-auto rounded-xl bg-zinc-100/65 p-4 font-mono text-[12px] leading-6 text-zinc-700 shadow-inner shadow-zinc-200/35 dark:bg-white/[0.04] dark:text-zinc-300 dark:shadow-black/10 lg:h-full lg:max-h-none',
  keycap: 'inline-flex min-h-6 items-center gap-1 rounded-md bg-gradient-to-b from-white to-zinc-100 px-1.5 py-0.5 font-mono text-[11px] font-medium text-zinc-600 shadow-[inset_0_1px_0_rgba(255,255,255,0.9),inset_0_-1px_0_rgba(39,39,42,0.12),0_1px_1px_rgba(39,39,42,0.14)] dark:from-zinc-800 dark:to-zinc-900 dark:text-zinc-300 dark:shadow-[inset_0_1px_0_rgba(255,255,255,0.09),inset_0_-1px_0_rgba(0,0,0,0.55),0_1px_1px_rgba(0,0,0,0.45)]',
  controlGroup: 'rounded-xl bg-zinc-100/75 p-1 dark:bg-white/[0.045]',
  iconButton: 'grid size-7 place-items-center rounded-lg bg-zinc-100/80 text-xs text-zinc-700 shadow-sm outline-none transition hover:bg-white active:translate-y-px active:bg-zinc-200/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 disabled:opacity-40 disabled:active:translate-y-0 dark:bg-white/[0.06] dark:text-zinc-300 dark:hover:bg-white/[0.08] dark:active:bg-white/[0.11] dark:focus-visible:outline-zinc-500',
  button: 'inline-flex h-8 items-center rounded-xl bg-zinc-100/80 px-3 text-sm font-medium text-zinc-800 shadow-sm outline-none transition hover:bg-white active:translate-y-px active:bg-zinc-200/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 aria-pressed:bg-zinc-900 aria-pressed:text-white disabled:opacity-40 disabled:active:translate-y-0 dark:bg-white/[0.06] dark:text-zinc-200 dark:hover:bg-white/[0.08] dark:active:bg-white/[0.11] dark:aria-pressed:bg-zinc-100 dark:aria-pressed:text-zinc-950 dark:focus-visible:outline-zinc-500',
  textButton: 'inline-flex h-8 items-center justify-center rounded-lg px-2.5 text-xs font-medium text-zinc-600 outline-none transition hover:bg-zinc-100 hover:text-zinc-950 active:translate-y-px focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 disabled:opacity-40 dark:text-zinc-400 dark:hover:bg-zinc-900 dark:hover:text-zinc-100 dark:focus-visible:outline-zinc-500',
  option: 'min-h-8 rounded-lg px-2.5 text-left text-xs font-medium text-zinc-600 outline-none transition hover:bg-white/70 hover:text-zinc-950 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 aria-selected:bg-white aria-selected:text-zinc-950 aria-selected:shadow-sm data-[focus-visible]:outline data-[focus-visible]:outline-2 data-[focus-visible]:outline-offset-2 data-[focus-visible]:outline-zinc-400 dark:text-zinc-400 dark:hover:bg-white/[0.06] dark:hover:text-zinc-100 dark:focus-visible:outline-zinc-500 dark:aria-selected:bg-zinc-100 dark:aria-selected:text-zinc-950 dark:data-[focus-visible]:outline-zinc-500',
  listOption: 'min-h-8 rounded-lg px-2.5 py-1.5 text-sm text-zinc-800 outline-none transition aria-disabled:text-zinc-400 aria-selected:bg-zinc-100 aria-selected:text-zinc-950 data-[active]:bg-white/75 data-[active]:text-zinc-950 data-[focus-visible]:outline data-[focus-visible]:outline-2 data-[focus-visible]:outline-offset-2 data-[focus-visible]:outline-zinc-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-zinc-400 dark:text-zinc-300 dark:aria-disabled:text-zinc-600 dark:aria-selected:bg-white/[0.07] dark:aria-selected:text-zinc-50 dark:data-[active]:bg-white/[0.055] dark:data-[active]:text-zinc-50 dark:data-[focus-visible]:outline-zinc-500 dark:focus-visible:outline-zinc-500',
} as const

export function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(' ')
}
