export const ds = {
  focusRing: 'outline-none ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 dark:ui-focus:outline-zinc-500',
  focusRingInset: 'outline-none ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-[-2px] ui-focus:outline-zinc-400 dark:ui-focus:outline-zinc-500',
  panel: 'min-h-0 rounded-md border border-zinc-200 bg-white p-3 dark:border-white/10 dark:bg-zinc-950',
  field: 'h-8 w-full rounded-md border border-zinc-200 bg-zinc-100/75 px-2.5 text-sm outline-none transition focus:bg-white ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 dark:border-white/10 dark:bg-white/[0.06] dark:focus:bg-white/[0.08] dark:ui-focus:outline-zinc-500',
  codeBlock: 'max-h-[44dvh] min-h-0 overflow-auto rounded-md bg-zinc-950 p-4 pr-12 font-mono text-[11px] leading-5 text-zinc-200 lg:h-full lg:max-h-none',
  dataBlock: 'max-h-[44dvh] min-h-0 overflow-auto rounded-md bg-zinc-100/65 p-4 font-mono text-[12px] leading-6 text-zinc-700 dark:bg-white/[0.04] dark:text-zinc-300 lg:h-full lg:max-h-none',
  controlGroup: 'rounded-md border border-zinc-200 p-1 dark:border-white/10',
  iconButton: 'grid size-7 place-items-center rounded-md bg-zinc-100/80 text-xs text-zinc-700 outline-none transition hover:bg-white ui-active:translate-y-px ui-active:bg-zinc-200/70 ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 ui-disabled:opacity-40 ui-disabled:ui-active:translate-y-0 dark:bg-white/[0.06] dark:text-zinc-300 dark:hover:bg-white/[0.08] dark:ui-active:bg-white/[0.11] dark:ui-focus:outline-zinc-500',
  button: 'inline-flex h-8 items-center rounded-md bg-zinc-100/80 px-3 text-sm font-medium text-zinc-800 outline-none transition hover:bg-white ui-active:translate-y-px ui-active:bg-zinc-200/70 ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 ui-pressed:bg-zinc-900 ui-pressed:text-white ui-disabled:opacity-40 ui-disabled:ui-active:translate-y-0 dark:bg-white/[0.06] dark:text-zinc-200 dark:hover:bg-white/[0.08] dark:ui-active:bg-white/[0.11] dark:ui-pressed:bg-zinc-100 dark:ui-pressed:text-zinc-950 dark:ui-focus:outline-zinc-500',
  textButton: 'inline-flex h-8 items-center justify-center rounded-lg px-2.5 text-xs font-medium text-zinc-600 outline-none transition hover:bg-zinc-100 hover:text-zinc-950 ui-active:translate-y-px ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 ui-disabled:opacity-40 dark:text-zinc-400 dark:hover:bg-zinc-900 dark:hover:text-zinc-100 dark:ui-focus:outline-zinc-500',
  option: 'min-h-8 rounded-md px-2.5 text-left text-xs font-medium text-zinc-600 outline-none transition hover:bg-white/70 hover:text-zinc-950 ui-active:bg-white/75 ui-active:text-zinc-950 ui-active:ring-1 ui-active:ring-inset ui-active:ring-zinc-300/70 ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 ui-focus:ring-2 ui-focus:ring-inset ui-focus:ring-zinc-400/30 ui-selected:bg-white ui-selected:text-zinc-950 ui-disabled:text-zinc-400 dark:text-zinc-400 dark:hover:bg-white/[0.06] dark:hover:text-zinc-100 dark:ui-active:bg-white/[0.055] dark:ui-active:text-zinc-50 dark:ui-active:ring-white/15 dark:ui-focus:outline-zinc-500 dark:ui-focus:ring-zinc-500/30 dark:ui-selected:bg-zinc-100 dark:ui-selected:text-zinc-950 dark:ui-disabled:text-zinc-600',
  listOption: 'min-h-8 rounded-lg px-2.5 py-1.5 text-sm text-zinc-800 outline-none transition ui-disabled:text-zinc-400 ui-selected:bg-zinc-100 ui-selected:text-zinc-950 ui-active:bg-white/75 ui-active:text-zinc-950 ui-active:ring-1 ui-active:ring-inset ui-active:ring-zinc-300/70 ui-focus:outline ui-focus:outline-2 ui-focus:outline-offset-2 ui-focus:outline-zinc-400 ui-focus:ring-2 ui-focus:ring-inset ui-focus:ring-zinc-400/30 dark:text-zinc-300 dark:ui-disabled:text-zinc-600 dark:ui-selected:bg-white/[0.07] dark:ui-selected:text-zinc-50 dark:ui-active:bg-white/[0.055] dark:ui-active:text-zinc-50 dark:ui-active:ring-white/15 dark:ui-focus:outline-zinc-500 dark:ui-focus:ring-zinc-500/30',
  checkable: 'ui-checked:bg-zinc-900 ui-checked:text-white dark:ui-checked:bg-zinc-100 dark:ui-checked:text-zinc-950',
  expandable: 'ui-expanded:bg-white ui-expanded:text-zinc-950 dark:ui-expanded:bg-zinc-100 dark:ui-expanded:text-zinc-950',
} as const

export function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(' ')
}
