export {
  InteractionActionDescriptorSchema,
  InteractionConditionSchema,
  InteractionFocusContainmentSchema,
  InteractionFocusDefinitionSchema,
  InteractionFocusGuardPolicySchema,
  InteractionFocusStrategySchema,
  InteractionFocusTargetSchema,
  InteractionKeyModifierSchema,
  InteractionKeyPlatformBindingSchema,
  InteractionKeyRuleDefinitionSchema,
  InteractionKeyRuleKindSchema,
  InteractionKeyTargetKindSchema,
  InteractionOwnerDefinitionKindSchema,
  InteractionOwnerDefinitionSchema,
  InteractionOwnerDefinitionsSchema,
  InteractionOwnerDiagnosticsDefinitionSchema,
  InteractionOwnerRuntimeKindSchema,
  InteractionOwnerScopeSchema,
  InteractionPlatformSchema,
  InteractionSerializableValueSchema,
  InteractionShellRulesDefinitionSchema,
  InteractionTargetPolicySchema,
  compileInteractionOwnerDefinition,
  compileInteractionOwnerDefinitions,
  defineInteractionOwner,
  defineInteractionOwners,
  evaluateInteractionCondition,
  type InteractionActionDescriptor,
  type InteractionCondition,
  type InteractionDefinitionKeyInput,
  type InteractionFocusContainment,
  type InteractionFocusDefinition,
  type InteractionFocusGuardPolicy,
  type InteractionFocusStrategy,
  type InteractionFocusTarget,
  type InteractionKeyModifier,
  type InteractionKeyPlatformBinding,
  type InteractionKeyRuleDefinition,
  type InteractionOwnerDefinition,
  type InteractionOwnerDefinitionKind,
  type InteractionOwnerDiagnosticsDefinition,
  type InteractionOwnerRuntimeKind,
  type InteractionOwnerScope,
  type InteractionShellRulesDefinition,
  type InteractionTargetPolicy,
} from './interactionDefinition'
