export {
  createInteractionOwnershipRegistry,
  matchInteractionKeyRule,
  resolveInteractionRestoreTarget,
  type InteractionKeyAction,
  type InteractionKeyInput,
  type InteractionKeyPlatformRule,
  type InteractionKeyTargetKind,
  type InteractionKeyRule,
  type InteractionKeyRuleKind,
  type InteractionMatchedKeyRule,
  type InteractionOwner,
  type InteractionOwnerDiagnostics,
  type InteractionOwnerId,
  type InteractionOwnerKind,
  type InteractionOwnershipRegistry,
  type InteractionOwnershipSnapshot,
  type InteractionPlatform,
  type InteractionRestoreInput,
  type InteractionRestoreReason,
  type InteractionRestoreTarget,
  type InteractionRestoreTargetKind,
  type InteractionRestoreTargetResolver,
  type InteractionSerializableValue,
} from './interactionOwnership'

export {
  InteractionActionDescriptorSchema,
  InteractionConditionSchema,
  InteractionFocusContainmentSchema,
  InteractionFocusDefinitionSchema,
  InteractionFocusGuardPolicySchema,
  InteractionFocusStrategySchema,
  InteractionFocusTargetSchema,
  InteractionKeyModifierSchema,
  InteractionKeyPlatformBindingSchema,
  InteractionKeyRuleDefinitionSchema,
  InteractionKeyRuleKindSchema,
  InteractionKeyTargetKindSchema,
  InteractionOwnerDefinitionKindSchema,
  InteractionOwnerDefinitionSchema,
  InteractionOwnerDefinitionsSchema,
  InteractionOwnerDiagnosticsDefinitionSchema,
  InteractionOwnerRuntimeKindSchema,
  InteractionOwnerScopeSchema,
  InteractionPlatformSchema,
  InteractionSerializableValueSchema,
  InteractionShellRulesDefinitionSchema,
  InteractionTargetPolicySchema,
  compileInteractionOwnerDefinition,
  compileInteractionOwnerDefinitions,
  defineInteractionOwner,
  defineInteractionOwners,
  evaluateInteractionCondition,
  type InteractionActionDescriptor,
  type InteractionCondition,
  type InteractionDefinitionKeyInput,
  type InteractionFocusContainment,
  type InteractionFocusStrategy,
  type InteractionFocusTarget,
  type InteractionKeyModifier,
  type InteractionKeyRuleDefinition,
  type InteractionOwnerDefinition,
  type InteractionOwnerDefinitionKind,
  type InteractionOwnerScope,
  type InteractionShellRulesDefinition,
  type InteractionTargetPolicy,
} from './interactionDefinition'

export {
  routeInteractionKey,
  type InteractionRouteReason,
  type InteractionRouteResult,
  type InteractionRouteStatus,
} from './interactionRouting'

export { classifyInteractionKeyTarget } from './interactionKeyTarget'

export {
  evaluateInteractionFocusGuard,
  evaluateInteractionFocusTarget,
  type InteractionFocusGuardAction,
  type InteractionFocusGuardInput,
  type InteractionFocusGuardReason,
  type InteractionFocusGuardResult,
} from './interactionFocusGuard'

export {
  createInteractionDiagnosticsSnapshot,
  describeInteractionDomFocus,
  type InteractionDiagnosticsOptions,
  type InteractionDiagnosticsSnapshot,
  type InteractionDomFocusSnapshot,
} from './interactionDiagnostics'

export {
  handleInteractionKeyboardEvent,
  interactionKeyInputFromKeyboardEvent,
  routeInteractionKeyboardEvent,
  type HandleInteractionKeyboardEventOptions,
  type InteractionKeyboardEventLike,
  type InteractionKeyboardEventRoute,
  type InteractionKeyboardRouteCallback,
} from './interactionKeyboardEvent'
